-- Agent Skills Database Schema
-- Compatible with PostgreSQL 13+

-- Skills table - stores skill metadata
CREATE TABLE skills (
    id VARCHAR(255) PRIMARY KEY,
    display_title VARCHAR(255) NOT NULL,
    description TEXT,
    source VARCHAR(50) NOT NULL CHECK (source IN ('provider', 'custom')),
    latest_version VARCHAR(100) NOT NULL,
    created_at BIGINT NOT NULL,
    updated_at BIGINT,
    provider VARCHAR(100),
    
    -- Indexes for performance
    INDEX idx_skills_source (source),
    INDEX idx_skills_created_at (created_at),
    INDEX idx_skills_provider (provider)
);

-- Skill versions table - stores different versions of skills
CREATE TABLE skill_versions (
    id VARCHAR(255) PRIMARY KEY,
    skill_id VARCHAR(255) NOT NULL REFERENCES skills(id) ON DELETE CASCADE,
    version VARCHAR(100) NOT NULL,
    created_at BIGINT NOT NULL,
    files JSONB NOT NULL, -- Stores file structure and metadata
    checksum VARCHAR(64), -- SHA-256 hash for integrity
    
    -- Ensure unique version per skill
    UNIQUE(skill_id, version),
    
    -- Indexes
    INDEX idx_skill_versions_skill_id (skill_id),
    INDEX idx_skill_versions_created_at (created_at),
    INDEX idx_skill_versions_version (version)
);

-- Files table - stores file metadata for files generated by skills
CREATE TABLE files (
    id VARCHAR(255) PRIMARY KEY,
    filename VARCHAR(255) NOT NULL,
    size_bytes BIGINT NOT NULL,
    created_at BIGINT NOT NULL,
    content_hash VARCHAR(64), -- SHA-256 hash
    mime_type VARCHAR(100),
    
    -- Optional links to skills
    skill_id VARCHAR(255) REFERENCES skills(id) ON DELETE SET NULL,
    skill_version_id VARCHAR(255) REFERENCES skill_versions(id) ON DELETE SET NULL,
    
    -- Indexes
    INDEX idx_files_skill_id (skill_id),
    INDEX idx_files_skill_version_id (skill_version_id),
    INDEX idx_files_created_at (created_at),
    INDEX idx_files_size_bytes (size_bytes)
);

-- Messages table - stores chat/messages for conversations
CREATE TABLE messages (
    id VARCHAR(255) PRIMARY KEY,
    conversation_id VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL CHECK (role IN ('user', 'assistant', 'system', 'tool')),
    content JSONB NOT NULL, -- Flexible content structure
    created_at BIGINT NOT NULL,
    
    -- Optional container/session info
    container_id VARCHAR(255),
    
    -- Links to skills used in this message
    skill_ids TEXT[], -- Array of skill IDs used
    
    -- Indexes
    INDEX idx_messages_conversation_id (conversation_id),
    INDEX idx_messages_created_at (created_at),
    INDEX idx_messages_role (role),
    INDEX idx_messages_container_id (container_id)
);

-- Containers table - tracks container/session state
CREATE TABLE containers (
    id VARCHAR(255) PRIMARY KEY,
    status VARCHAR(50) NOT NULL DEFAULT 'running' CHECK (status IN ('running', 'stopped', 'error')),
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    skills_enabled TEXT[], -- Array of skill IDs enabled in this container
    metadata JSONB, -- Additional container metadata
    
    -- Indexes
    INDEX idx_containers_status (status),
    INDEX idx_containers_created_at (created_at),
    INDEX idx_containers_updated_at (updated_at)
);

-- Container executions table - logs code executions
CREATE TABLE container_executions (
    id VARCHAR(255) PRIMARY KEY,
    container_id VARCHAR(255) NOT NULL REFERENCES containers(id) ON DELETE CASCADE,
    skill_id VARCHAR(255) REFERENCES skills(id) ON DELETE SET NULL,
    code TEXT NOT NULL,
    output TEXT,
    error_message TEXT,
    status VARCHAR(50) NOT NULL CHECK (status IN ('running', 'completed', 'failed')),
    started_at BIGINT NOT NULL,
    completed_at BIGINT,
    execution_time_ms INTEGER,
    
    -- Indexes
    INDEX idx_executions_container_id (container_id),
    INDEX idx_executions_skill_id (skill_id),
    INDEX idx_executions_status (status),
    INDEX idx_executions_started_at (started_at)
);

-- Users table - for authentication and user management
CREATE TABLE users (
    id VARCHAR(255) PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    username VARCHAR(100) UNIQUE,
    created_at BIGINT NOT NULL,
    updated_at BIGINT,
    is_active BOOLEAN DEFAULT true,
    
    -- Indexes
    INDEX idx_users_email (email),
    INDEX idx_users_username (username),
    INDEX idx_users_created_at (created_at)
);

-- User skills table - tracks which skills are installed/available to users
CREATE TABLE user_skills (
    id VARCHAR(255) PRIMARY KEY,
    user_id VARCHAR(255) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    skill_id VARCHAR(255) NOT NULL REFERENCES skills(id) ON DELETE CASCADE,
    installed_at BIGINT NOT NULL,
    is_favorite BOOLEAN DEFAULT false,
    
    -- Ensure unique skill per user
    UNIQUE(user_id, skill_id),
    
    -- Indexes
    INDEX idx_user_skills_user_id (user_id),
    INDEX idx_user_skills_skill_id (skill_id),
    INDEX idx_user_skills_installed_at (installed_at)
);

-- Function to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = EXTRACT(EPOCH FROM NOW()) * 1000;
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Triggers for automatic updated_at updates
CREATE TRIGGER update_skills_updated_at BEFORE UPDATE ON skills
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_users_updated_at BEFORE UPDATE ON users
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_containers_updated_at BEFORE UPDATE ON containers
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- Views for common queries
CREATE VIEW skill_stats AS
SELECT 
    s.id,
    s.display_title,
    s.source,
    s.latest_version,
    s.created_at,
    COUNT(sv.id) as version_count,
    COUNT(DISTINCT us.user_id) as user_count
FROM skills s
LEFT JOIN skill_versions sv ON s.id = sv.skill_id
LEFT JOIN user_skills us ON s.id = us.skill_id
GROUP BY s.id, s.display_title, s.source, s.latest_version, s.created_at;

CREATE VIEW container_status_summary AS
SELECT 
    status,
    COUNT(*) as count,
    AVG(updated_at - created_at) as avg_lifetime_ms
FROM containers 
GROUP BY status;

-- Insert some sample data for testing
INSERT INTO skills (id, display_title, description, source, latest_version, created_at, provider) VALUES
('skill_pptx', 'PowerPoint Generator', 'Generate PowerPoint presentations from text content', 'provider', '20251013', 1759178010641129, 'internal'),
('skill_excel', 'Excel Data Processor', 'Process and analyze Excel spreadsheets', 'provider', '20251013', 1759178010641129, 'internal'),
('skill_custom_001', 'Custom Web Scraper', 'Custom skill for web scraping tasks', 'custom', '1759178010641129', 1759178010641129, NULL);

INSERT INTO skill_versions (id, skill_id, version, created_at, files, checksum) VALUES
('ver_pptx_001', 'skill_pptx', '20251013', 1759178010641129, '{"files": [{"path": "SKILL.md", "type": "manifest"}, {"path": "main.py", "type": "code"}]}', 'sha256_hash_placeholder'),
('ver_excel_001', 'skill_excel', '20251013', 1759178010641129, '{"files": [{"path": "SKILL.md", "type": "manifest"}, {"path": "processor.py", "type": "code"}]}', 'sha256_hash_placeholder');

-- Comments for documentation
COMMENT ON TABLE skills IS 'Stores skill metadata and configuration';
COMMENT ON TABLE skill_versions IS 'Stores different versions of skills with their file structures';
COMMENT ON TABLE files IS 'Stores metadata for files generated by skills during execution';
COMMENT ON TABLE messages IS 'Stores chat/messages for conversations with optional skill integration';
COMMENT ON TABLE containers IS 'Tracks container/session state for skill execution';
COMMENT ON TABLE container_executions IS 'Logs all code executions within containers';
COMMENT ON TABLE users IS 'User accounts for authentication and skill management';
COMMENT ON TABLE user_skills IS 'Tracks which skills are installed/available to each user';